# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved_admins',
            field=models.ManyToManyField(blank=True, help_text='Admin users who have been approved to access this company', related_name='accessible_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
