# Generated by Django 5.2.7 on 2025-10-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_approved_admins'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the resource listing', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the resources and requirements')),
                ('start_date', models.DateField(help_text='Date from which resources are available')),
                ('expected_end_date', models.DateField(blank=True, help_text='Expected end date of availability', null=True)),
                ('total_resources', models.PositiveIntegerField(default=0, help_text='Total number of resources in this listing')),
                ('skills_summary', models.TextField(blank=True, help_text='Comma-separated summary of available skills')),
                ('locations', models.TextField(blank=True, help_text='Available locations (extensible field for future use)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_params', models.JSONField(blank=True, default=dict, help_text='Extensible field for additional parameters')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_listings', to='companies.company')),
                ('employees', models.ManyToManyField(help_text='Employees included in this resource listing', related_name='resource_listings', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Resource Listing',
                'verbose_name_plural': 'Resource Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message from requesting company')),
                ('response', models.TextField(blank=True, help_text='Response from resource owner company')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('additional_params', models.JSONField(blank=True, default=dict, help_text='Extensible field for additional request parameters')),
                ('requesting_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to='companies.company')),
                ('resource_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='employees.resourcelisting')),
            ],
            options={
                'verbose_name': 'Resource Request',
                'verbose_name_plural': 'Resource Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resourcelisting',
            index=models.Index(fields=['company', 'status'], name='employees_r_company_4d2005_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelisting',
            index=models.Index(fields=['start_date'], name='employees_r_start_d_2e816d_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelisting',
            index=models.Index(fields=['-created_at'], name='employees_r_created_936abb_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['requesting_company', 'status'], name='employees_r_request_bffc42_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['resource_listing', 'status'], name='employees_r_resourc_3978b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerequest',
            unique_together={('resource_listing', 'requesting_company', 'status')},
        ),
    ]
